name: dartstruct_generator
description: dartstruct generator is an annotation processor generator using source_gen and inspired by Java MapStruct.
version: 0.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.5
  code_builder: ^3.2.1
  dart_style: ^1.3.3
  analyzer: ^3.0.0
  recase: ^3.0.0
  logging: ^0.11.4
  equatable: ^1.1.1
  dartstruct:
    path: ../core

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
